image: "python:3.6.4"

stages:
  - build
  - deploy 

before_script:
  - apt-get update -qq && apt-get install -y -qq zip jq
  - pip3 install awscli virtualenv
  
build:
  stage: build
  script:
    - ./bin/build.sh
  artifacts:
    paths:
    - LUAUTagger.zip
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - ./bin/deploy.sh

  